version: "3.7"
services:
    app:
        image: sireax/foodsaver-backend
        container_name: foodsaver-backend
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - default
    db:
        image: mysql:5.7
        container_name: foodsaver-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: foodsaver
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: foodsaver
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - default

    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - default
networks:
    default:
        ipam:
            driver: default
            config:
                -   subnet: 172.33.0.0/16
